name = "GpuNN"
uuid = "485772ff-6d57-4e7b-9fcc-ae3bae390afc"
authors = ["Paweł Renc <prenc@agh.edu.pl>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
